services:
  - type: web
    name: discord-bot-sasha
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: OWNER_ID
        value: 736990837254258838
      - key: PYTHON_VERSION
        value: 3.11.9
